<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-UPJ4O7I" failures="2" tests="9" name="Failed_Test" time="1.284" errors="0" timestamp="2023-07-12T13:10:52 IST">
  <testcase classname="FailTestCaseExecution.Demo" name="Test1" time="0.17">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="FailTestCaseExecution.Demo" name="Test1" time="0.017">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="FailTestCaseExecution.Demo" name="Test1" time="0.026">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="FailTestCaseExecution.Demo" name="Test1" time="0.048">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at FailTestCaseExecution.Demo.Test1(Demo.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="FailTestCaseExecution.Demo" name="Test2" time="0.014">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="FailTestCaseExecution.Demo" name="Test2" time="0.023">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="FailTestCaseExecution.Demo" name="Test2" time="0.024">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="FailTestCaseExecution.Demo" name="Test2" time="0.034">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at FailTestCaseExecution.Demo.Test2(Demo.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase classname="FailTestCaseExecution.Demo" name="Test3" time="0.018"/>
</testsuite> <!-- Failed_Test -->
